In [1]:
# ==========================================
# MindSense AI
# Data Understanding
# Version: 1.0
# Date: 16 July 2026
# ==========================================

import pandas as pd

In [2]:
# Load Dataset

df = pd.read_csv("../Dataset/Raw/MindSense_AI_Selected_Dataset_v1.csv")

In [3]:
# Display the first five records

df.head()

,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,Pooja,Female,37,Ghaziabad,Working Professional,Teacher,NaN,2.0,NaN,NaN,4.0,7-8 hours,Moderate,MA,No,6,2,No,No
1,Reyansh,Male,60,Kalyan,Working Professional,Financial Analyst,NaN,4.0,NaN,NaN,3.0,5-6 hours,Unhealthy,B.Com,Yes,0,4,Yes,No
2,Manvi,Female,42,Bhopal,Working Professional,Teacher,NaN,2.0,NaN,NaN,3.0,5-6 hours,Moderate,M.Com,No,0,2,No,No
3,Isha,Female,44,Thane,Working Professional,Teacher,NaN,3.0,NaN,NaN,5.0,7-8 hours,Healthy,MD,Yes,1,2,Yes,No
4,Aarav,Male,48,Indore,Working Professional,UX/UI Designer,NaN,4.0,NaN,NaN,3.0,7-8 hours,Moderate,BE,Yes,6,5,Yes,No

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2556 entries, 0 to 2555
Data columns (total 19 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Name                                   2556 non-null   str
 1   Gender                                 2556 non-null   str
 2   Age                                    2556 non-null   int64
 3   City                                   2556 non-null   str
 4   Working Professional or Student        2556 non-null   str
 5   Profession                             1883 non-null   str
 6   Academic Pressure                      502 non-null    float64
 7   Work Pressure                          2054 non-null   float64
 8   CGPA                                   502 non-null    float64
 9   Study Satisfaction                     502 non-null    float64
 10  Job Satisfaction                       2054 non-null   float64
 11  Sleep Duration                         2556 non-null   str
 12  Dietary Habits                         2556 non-null   str
 13  Degree                                 2556 non-null   str
 14  Have you ever had suicidal thoughts ?  2556 non-null   str
 15  Work/Study Hours                       2556 non-null   int64
 16  Financial Stress                       2556 non-null   int64
 17  Family History of Mental Illness       2556 non-null   str
 18  Depression                             2556 non-null   str
dtypes: float64(5), int64(3), str(11)
memory usage: 379.5 KB

In [5]:
df["Working Professional or Student"].value_counts()

Working Professional or Student
Working Professional    2054
Student                  502
Name: count, dtype: int64

In [6]:
df["Depression"].value_counts()

Depression
No     2101
Yes     455
Name: count, dtype: int64

In [7]:
df.dtypes

Name                                         str
Gender                                       str
Age                                        int64
City                                         str
Working Professional or Student              str
Profession                                   str
Academic Pressure                        float64
Work Pressure                            float64
CGPA                                     float64
Study Satisfaction                       float64
Job Satisfaction                         float64
Sleep Duration                               str
Dietary Habits                               str
Degree                                       str
Have you ever had suicidal thoughts ?        str
Work/Study Hours                           int64
Financial Stress                           int64
Family History of Mental Illness             str
Depression                                   str
dtype: object

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.describe()

,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Work/Study Hours,Financial Stress
count,2556.000000,502.000000,2054.000000,502.000000,502.000000,2054.000000,2556.000000,2556.000000
mean,39.043036,3.003984,3.021908,7.567809,3.075697,3.015093,6.023865,2.968701
std,12.260596,1.390007,1.417312,1.465367,1.373490,1.418432,3.771743,1.415527
min,18.000000,1.000000,1.000000,5.030000,1.000000,1.000000,0.000000,1.000000
25%,28.000000,2.000000,2.000000,6.210000,2.000000,2.000000,3.000000,2.000000
50%,39.000000,3.000000,3.000000,7.605000,3.000000,3.000000,6.000000,3.000000
75%,50.000000,4.000000,4.000000,8.825000,4.000000,4.000000,9.000000,4.000000
max,60.000000,5.000000,5.000000,10.000000,5.000000,5.000000,12.000000,5.000000